:bug: Also remove old files when removing from the db

diff --git a/.github/workflows/repo-remove.yml b/.github/workflows/repo-remove.yml
--- a/.github/workflows/repo-remove.yml
+++ b/.github/workflows/repo-remove.yml
@@ -58,7 +58,9 @@ jobs:
             for arch in x86_64 aarch64; do
               for branch in stable testing unstable; do
                 repo_dir=docs/$branch/$arch
-                repo-remove $repo_dir/manjaro-sway.db.tar.gz ${{ inputs.package }}
+                rm $repo_dir/${{ inputs.package }}-*.pkg.tar.zst
+                rm $repo_dir/${{ inputs.package }}-*.pkg.tar.zst.sig
+                repo-remove $repo_dir/manjaro-sway.db.tar.gz ${{ inputs.package }} || echo 'package not found'
               done
             done
   
